version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop_user
      MYSQL_PASSWORD: prestashop_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  prestashop:
    platform: linux/x86_64
    image: prestashop/prestashop:latest
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop_user
      DB_PASSWD: prestashop_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./prestashop_data:/var/www/html

  nodejs-app:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - mysql

volumes:
  mysql_data:
  prestashop_data:
